
platform :ios, '11.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'oem-intercom' do
  use_frameworks!
  pod 'RozcomOem', '0.1.7'
  pod 'NVActivityIndicatorView', '4.8.0'
  pod 'QMChatViewController', '0.6.6'
  pod 'Alamofire', '5.2.2'
  pod 'SwiftyJSON', '5.0.0'
  pod 'Quickblox-WebRTC', '2.7.5'
  pod 'FFCircularProgressView'
  pod 'SDWebImage', '~> 4.4.6'
end

# Set debug information to dwarf
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf'
        end
    end
end
