
platform :ios, '11.0'

target 'oem-intercom' do
  use_frameworks!
  pod 'RozcomOem'
  pod 'NVActivityIndicatorView', '4.8.0'
  pod 'QMChatViewController', '0.6.6'
  pod 'Alamofire', '5.1.0'
  pod 'SwiftyJSON', '5.0.0'
  pod 'Quickblox-WebRTC','~> 2.7'
  pod 'FFCircularProgressView'
  pod 'SDWebImage', '~> 4.4.6'
end
